version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - expense_network
  db:
    image: mysql:8.0
    container_name: smart_expense_splitter_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: smart_expense_splitter
    ports:
      - "3306:3306"
    networks:
      - expense_network
networks:
  expense_network:
    driver: bridge